services:
  backend:
    container_name: 'kpd-backend'
    build:
      context: backend
      dockerfile: Dockerfile
    image: 'kpd-backend'
    restart: on-failure
    env_file: .env
    ports:
      - '4000:3000'
    depends_on:
      - postgres
    # restart: on-failure
    networks:
      - backend

  postgres:
    container_name: 'postgres'
    image: postgres:alpine
    restart: on-failure
    env_file: .env
    ports:
      - '5432:5432'
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - backend

  frontend:
    container_name: 'kpd-frontend'
    build:
      context: frontend
      dockerfile: Dockerfile
    image: 'kpd-frontend'
    restart: on-failure
    env_file: .env
    ports:
      - '8081:80'
    networks:
      - frontend

  adminer:
    image: adminer
    restart: on-failure
    ports:
      - '8080:8080'
    networks:
      - backend

networks:
  backend:
  frontend:

volumes:
  pgdata: